[[track]]
path = "http://radio.cliamp.stream/lofi/stream"
title = "Lofi"

[[track]]
path = "https://www.youtube.com/watch?v=-OekvEFm1lo"
title = "Rain"

[[track]]
path = "https://www.youtube.com/watch?v=A8jDx9TLMQc"
title = "Jazz"
